import { Container } from 'lucide-react';
import { definePlugin } from '@/platform';

export default definePlugin({
  id: 'container-manager',
  label: "Containers",
  icon: Container,
  description:
    "Manage containers, images, volumes, and networks across Docker-compatible runtimes (colima, Docker Desktop, Rancher Desktop, OrbStack, Podman): live CPU/memory usage, CPU and memory limits editable one-by-one or across a selection, and Compose projects grouped read-only by container label.",
  keywords: ["docker", "colima", "podman", "rancher desktop", "orbstack", "container", "compose", "docker-compose", "image", "volume", "network", "dockerfile", "containerd", "cpu", "memory", "resource", "limits", "stats", "quota", "prune", "disk usage", "tag", "subnet", "ipam"],
  route: '/container-manager',
  order: 190,
  defaultEnabled: false,
  permissions: ['storage', 'files:write', 'clipboard:read', 'clipboard:write', 'native', 'service'],
  commands: ['mcp_respond'],
  service: {
    bin: 'devtool-svc-container',
    methods: [
      'list-configs',
      'save-config',
      'delete-config',
      'detect-sockets',
      'test-connection',
      'list',
      'inspect',
      'start',
      'stop',
      'restart',
      'pause',
      'unpause',
      'remove',
      'details',
      'resources',
      'update-resources',
      'logs-start',
      'logs-unsubscribe',
      'stats-start',
      'stats-unsubscribe',
      'stats-snapshot',
      'container-prune',
      'image-list',
      'image-inspect',
      'image-details',
      'image-remove',
      'image-pull',
      'image-prune',
      'image-tag',
      'volume-list',
      'volume-remove',
      'volume-create',
      'volume-sizes',
      'volume-prune',
      'volume-details',
      'network-list',
      'network-remove',
      'network-create',
      'network-prune',
      'network-details',
      'system-info',
      'system-df',
    ],
  },
  sdk: '^1.0.0',
  load: () => import('@/components/tools/container/ContainerManager').then((m) => m.ContainerManager),
});
